# Занятие 1
# Прикладная алгебра и численные методы
## Матрицы и системы линейных алгебраических уравнений (СЛАУ)
numpy:
https://numpy.org/doc/stable/reference/routines.linalg.html

scipy:
https://docs.scipy.org/doc/scipy/reference/linalg.html

In [1]:
import numpy as np

## Матрицы, действия с матрицами
В numpy в роли матриц могут использоваться списки list, например, так можно перемножать матрицы с помощью dot

In [2]:
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
display(a, b, np.dot(a, b))

[[1, 2], [3, 4]]

[[5, 6], [7, 8]]

array([[19, 22],
       [43, 50]])

Заметим, что dot возвращает не список, а array.

Для сложения матриц списки не годятся, при сложении списков получается добавление второго слагаемого в "хвост" первому:

In [3]:
a + b

[[1, 2], [3, 4], [5, 6], [7, 8]]

Для сложения и вычитания матриц можно использовать array:

In [4]:
a_np = np.array(a)
b_np = np.array(b)
display(a_np + b_np, a_np - b_np)

array([[ 6,  8],
       [10, 12]])

array([[-4, -4],
       [-4, -4]])

На основе списка можно сделать и матрицу matrix, на пример, с помощью mat

In [5]:
np.mat(a)

matrix([[1, 2],
        [3, 4]])

В последней версии numpy не рекомендуется использовать матрицы matrix, поскольку от них в будущем планируется избавиться, вместо них рекомендуется использовать array.

## Транспонирование
Для транспонирования матрицы используется np.transpose(x)

In [6]:
display(np.transpose(a), np.transpose(a_np))

array([[1, 3],
       [2, 4]])

array([[1, 3],
       [2, 4]])

np.transpose возвращает array и в случае, если в качестве аргумента передан array, и если аргумент - list.

## Функции в Python
Для более наглядного и удобного решения задачи былает удобно разбить ее на подзадачи и каждую подзадачу оформить в виде функции. Функции бывают встроенные, такие как $\sin$ и $\log$, их можно использовать, подключив соответствующий модуль. Можно написать собственные функции следующим образом:

def function_name(arg1,\ ...,\ arg2=Value):

    .....
    
    return something
Ключевое слово return можно опустить, тогда функция вернет в качестве результата None.

У функции могут быть только обязательные аргументы, но могут быть и аргументы со значениями по умолчанию (необязательные аргументы).
Вначале опишем функцию $f$ с обязательными аргументами $x$ и $a$.

При вызове функции аргументы передаются по порядку, в нашем случае сначала значение  $x$, потом $a$.

### Пример 1
Опишем функцию $func\_power(x, a) = x^a$:    

In [7]:
def func_power(x, a):
    return x**a

При вызове функции сначала передаем значение  $x$, потом $a$. 

In [8]:
func_power(2, 3)

8

### Необязательные аргументы
Необязательные аргументы или аргументы со значением по умолчанию передаются всегда ПОСЛЕ обязательных аргументов!!!
### Пример 2
Опишем функцию $g(A, n) = A^n$ с параметром $n$, по умолчанию равным 1:

In [9]:
def g(A, n=1):
    return A**n

При вызове функции передадим только обязательный аргумент, если нас устраивает значение по умолчанию

In [10]:
A = np.mat([[1, 2], [3, 4]])
g(A)

matrix([[1, 2],
        [3, 4]])

Возведем матрицу в степень 3:

In [11]:
g(A, 3)

matrix([[ 37,  54],
        [ 81, 118]])

Если вместо матрицы matrix использовать array, результат будет другим:

In [12]:
B = np.array([[1, 2], [3, 4]])
g(B, 3)

array([[ 1,  8],
       [27, 64]], dtype=int32)

Для того, чтобы перемножить два array как матрицы, нужно использовать функцию matmul

In [13]:
np.matmul(A, B)

matrix([[ 7, 10],
        [15, 22]])

У matmul есть необязательный аргумент - матрица (array), куда нужно записать результат:

In [14]:
C = np.ones((2, 2))
display(C)
np.matmul(B, B, C)
display(C)

array([[1., 1.],
       [1., 1.]])

array([[ 7., 10.],
       [15., 22.]])

Можно вместо array использовать matrix, пока работает:

In [15]:
display(A)
np.matmul(B, B, A)
display(A)

matrix([[1, 2],
        [3, 4]])

matrix([[ 7, 10],
        [15, 22]])

### Пример 3
Перепишем функцию $g(A, n) = A^n$ Примера 2 так, чтобы и array перемножались как матрицы:

In [16]:
def g3(A, n=1):
    if n < 1:
        return 'error'
    if n == 1:
        return A
    res = A.copy()
    for k in range(n - 1):
        np.matmul(res, A, res)
    return res

In [17]:
display(g3(B), g3(B, 3))

array([[1, 2],
       [3, 4]])

array([[ 37,  54],
       [ 81, 118]])

In [18]:
np.matmul(B, np.matmul(B, B))

array([[ 37,  54],
       [ 81, 118]])

## Аргументы функции, число которых заранее неизвестно
### Пример 4
Перепишем функцию $g3$ Примера 3 так, чтобы с ее помощью можно было находить произведение произвольного числа матриц:

In [19]:
def g4(*args):
    n = len(args)
    if  n == 0:
        return 'error'
    if n == 1:
        return args[0]
    res = args[0].copy()
    for k in range(1, n):
        np.matmul(res, args[k], res)
    return res

In [20]:
g4(A)

matrix([[ 7, 10],
        [15, 22]])

In [21]:
g4(A, B, A)

matrix([[1069, 1558],
        [2337, 3406]])

In [22]:
g4(B, B, A)

array([[199, 290],
       [435, 634]])

Заметим, что тип результата такой, как у первого аргумента.

### Пример 5.
Решим СЛАУ
$$
\left\{
\begin{matrix}
2x + 3y - z = 5\\
3x - 2y + z = 2\\
x + y - z = 0
\end{matrix}
\right.
$$
Для решения СЛАУ воспользуемся linalg.solve, аргументы - матрица левой части и столбец правой.

Для проверки правильности решения используем allclose

In [23]:
a = np.array([[2, 3, -1], [3, -2, 1], [1, 1, -1]])
b = np.array([5, 2, 0])
x = np.linalg.solve(a, b)
display(x)
np.allclose(np.dot(a, x), b)

array([1., 2., 3.])

True