<a href="https://colab.research.google.com/github/GalinaZh/Appl_alg2021/blob/main/iterations_examples_DP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


## Метод Зейделя

In [2]:
def F(P, B, X): 
    return P @ X + B

In [3]:
P = -0.01*np.array([[0, 15, 5], [10, 0, 15], [30, 10, 0]])
B = np.array([[3.4], [2.05], [6]])
x0 = F(P, B, np.zeros((3, 1)))
display(P, B, x0)

array([[-0.  , -0.15, -0.05],
       [-0.1 , -0.  , -0.15],
       [-0.3 , -0.1 , -0.  ]])

array([[3.4 ],
       [2.05],
       [6.  ]])

array([[3.4 ],
       [2.05],
       [6.  ]])

In [5]:
x = x0;
for i in range(15):
    x = F(P, B, x)
    print(x.T)

[[2.7925 0.81   4.775 ]]
[[3.03975 1.0545  5.08125]]
[[2.9877625 0.9838375 4.982625 ]]
[[3.00329312 1.00383    5.0052875 ]]
[[2.99916113 0.99887756 4.99862906]]
[[3.00023691 1.00028953 5.00036391]]
[[2.99993838 0.99992172 4.99989997]]
[[3.00001674 1.00002117 5.00002632]]
[[2.99999551 0.99999438 4.99999286]]
[[3.0000012  1.00000152 5.00000191]]
[[2.99999968 0.99999959 4.99999949]]
[[3.00000009 1.00000011 5.00000014]]
[[2.99999998 0.99999997 4.99999996]]
[[3.00000001 1.00000001 5.00000001]]
[[3. 1. 5.]]


In [ ]:
nP= np.linalg.norm(P, np.inf); nP

0.4

In [ ]:
eps= 0.001;

In [ ]:
x=F(np.zeros((3,1)));
for i in range(11):
    if (np.linalg.norm(x-F(x), np.inf)/(1-nP)<eps):
        print(i, x)
    x=F(x)
    

6 [[3.00023691]
 [1.00028953]
 [5.00036391]]
7 [[2.99993838]
 [0.99992172]
 [4.99989997]]
8 [[3.00001674]
 [1.00002117]
 [5.00002632]]
9 [[2.99999551]
 [0.99999438]
 [4.99999286]]
10 [[3.0000012 ]
 [1.00000152]
 [5.00000191]]


In [ ]:
x=F(np.zeros((3,1)));
for i in range(11):
    if (np.linalg.norm(x-F(x), np.inf)<eps):
        print(i, x)
    x=F(x)

In [ ]:
EminusP1= np.eye(3)+0.01*np.array([[0, 0,0],[10,0,0],[30,10,0]]);

In [ ]:
EminusP1

array([[1. , 0. , 0. ],
       [0.1, 1. , 0. ],
       [0.3, 0.1, 1. ]])

In [ ]:
P2 = -0.01*np.array([[0, 15, 5],[0,0,15],[0,0,0]]);


In [ ]:
P2

array([[-0.  , -0.15, -0.05],
       [-0.  , -0.  , -0.15],
       [-0.  , -0.  , -0.  ]])

In [ ]:
np.linalg.inv(EminusP1)

array([[ 1.  ,  0.  ,  0.  ],
       [-0.1 ,  1.  ,  0.  ],
       [-0.29, -0.1 ,  1.  ]])

In [ ]:
def Fzeig(X):
    return np.linalg.inv(EminusP1)@(P2@X+B);

In [ ]:
x=Fzeig(np.zeros((3,1)));

In [ ]:
x=Fzeig(np.zeros((3,1)));
for i in range(11):
    if (np.linalg.norm(x-Fzeig(x), np.inf)/(1-nP)<eps):
        print(i, x)
    x=Fzeig(x)

3 [[3.00034228]
 [0.99960384]
 [4.99993693]]
4 [[3.00006258]
 [1.0000032 ]
 [4.99998091]]
5 [[3.00000047]
 [1.00000282]
 [4.99999958]]
6 [[2.9999996 ]
 [1.0000001 ]
 [5.00000011]]
7 [[2.99999998]
 [0.99999999]
 [5.00000001]]
8 [[3.]
 [1.]
 [5.]]
9 [[3.]
 [1.]
 [5.]]
10 [[3.]
 [1.]
 [5.]]
